# Generated by Django 4.2 on 2023-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "General Audiences"),
                    ("PG", "Parental Guidance Suggested"),
                    ("PG_13", "Parents Strongly Cautioned"),
                    ("R", "Restricted"),
                    ("NC_17", "Adults Only"),
                ],
                default="G",
                max_length=20,
                null=True,
            ),
        ),
    ]
