# Generated by Django 4.2 on 2023-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "General Audiences"),
                    ("PG", "Parental Guidance Suggested"),
                    ("PG-13", "Parents Strongly Cautioned"),
                    ("R", "Restricted"),
                    ("NC-17", "Adults Only"),
                ],
                default="G",
                max_length=20,
                null=True,
            ),
        ),
    ]
