# Generated by Django 4.2 on 2023-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_movie_duration_alter_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
