# Generated by Django 4.2 on 2023-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
